### ISSUE TITLE
Dumping a field with a dictionary field creates a new group

### ISSUE THREAD

**Issue by HenningDinero** [hukkin/tomli-w#72]
Say I have a `pyproject.toml` for poetry

```toml
[tool.poetry]
name = "div-utils"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.12"
tomli-w = "^1.2.0"
tomli = {version="^2.2.1", source="PyPI"}


[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
```

and I load that 

```python
import tomli
with open(path/"pyproject.toml", "rb") as f:
      toml_dict_old = tomli.load(f)
toml_dict_old["tool"]["poetry"]["dependencies"]["tomli"] # {'version': '^2.2.1', 'source': 'PyPI'}
``` 

now, if I dumpt the same object using `tomli-w``

```python
import tomli_w
  with open(path/"pyproject_test.toml", "wb") as f:
      tomli_w.dump(toml_dict_old,f)
```
then  we get the dependencies as 

```toml
[tool.poetry.dependencies]
python = "^3.12"
tomli-w = "^1.2.0"

[tool.poetry.dependencies.tomli]
version = "^3.0.0"
source = "PyPI"
```

As you can see the `tomli` part is now its own "group" and not a part of the dependencies.

Is there a way to overcome this? I would expect the outcome to be the same as  the input
