### ISSUE TITLE
Input is not equal to output when using tomli and tomli_w together

### ISSUE THREAD

**Issue by fdev31** [hukkin/tomli-w#73]
When some escapes are present in multiline strings, eg:

```toml
[foo]
maps = """xdg-open \"https://www.google.com/maps/place/$(wl-paste | sed -E 's/[ 	\\n]/+/g')\"'"""
```

When using tomli_w to reformat the toml content, eg:
```python
#!/bin/env python
"""
This script reformats TOML files. It reads from a file provided as a command-line
argument or from stdin if no argument is given, and outputs the reformatted TOML.
"""

import sys
import fileinput
import tomli
import tomli_w

with fileinput.input() as f:
    content = "\n".join(l for l in fileinput.input())
    obj = tomli.loads(content)
print(tomli_w.dumps(obj, multiline_strings=True))
```

then newlines are added at first and last character in the multiline-string.
